language: node_js
node_js:
- 0.12
notifications:
  slack:
    secure: dzbkWL7wMUCLBEafjs4ya1d+NMtUKsJ6apx6V7t6p0+R/uOR3IJ+TdtoSqVYeHyuzZ8PsWeN3rjUPIYvP+nxR6OWk8qnPWBOun4gSJOJfrc5/vZdjdu8tMQUokWetqNbe4NTUkKMbXK5+3HSEoYSYXJ26Vl2ewRhmYYK+MS8THoKf6BxbKTKwnmG8lg8yz6Zf5184hjkwJIyOguHQ0GyPH913r7ZT5sVKjtkI9PBk9kSqwbARarxn0hJtjm9mWHkurvlQT8X89VURj6UPjPdKibtSnbP7NnXo+VFFfWm6WohNqDvRH1Q8eX5/iK/v/LST8J7n0GTADWLjUv0tSPWCcyO+bBnUeSkMdTd7Rb6jkpcJJ6SmomFHs2CsBYUPJJj92h34u6bLyTBYkbCKHlVu1Z30lU5oxv0SKAboKra2uvgSA1D3rqwycmAYJfCGD8+RRwnrYE86zDOLV08X5MmTam/Pf9iXeOdUsYify0QnPqVh3zEG/zOG/F/Y4GDttwcNIzva0DicsnCy94MlOkTCqFPhUAyjRQaMzbconQ7bhFUKUYA9oJbVbDBG1jhXRvWGBSgD5VzA9PcS0ZU34fftTEbE3GjRfIRMBrTPtvWu9yrRIIt/Q/LwqBABraUcD/GJo1evpxwgIinOuH+uf6knal012fThGrAbclkfcGZ3JQ=
